# Copyright (c) 2026 dilocash
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file.

version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: dilocash-db
    environment:
      POSTGRES_USER: dilocash
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dilocash
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: dilocash-cache
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4
    container_name: dilocash-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dilocash.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

volumes:
  postgres_data:
