# Copyright (c) 2026 dilocash
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file.

version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: dilocash-cache
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4
    container_name: dilocash-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dilocash.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./scripts/pgadmin/servers.json:/pgadmin4/servers.json

volumes:
  pgadmin_data:
